### ISSUE TITLE
Plugin CsvView could not be found (cake 3.9)

### ISSUE THREAD

**Issue by r0bchain** [FriendsOfCake/cakephp-csvview#137]
I followed all the simple steps to install this plugin, but I get this error. (I am on cake 3.9)
```
2023-02-13 12:58:57 Error: [Cake\Core\Exception\MissingPluginException] Plugin CsvView could not be found. in /var/www/html/vendor/cakephp/cakephp/src/Core/PluginCollection.php on line 137
Stack Trace:
#0 /var/www/html/vendor/cakephp/cakephp/src/Http/BaseApplication.php(161): Cake\Core\PluginCollection->findPath('CsvView')
#1 /var/www/html/vendor/cakephp/cakephp/src/Http/BaseApplication.php(98): Cake\Http\BaseApplication->makePlugin('CsvView', Array)
#2 /var/www/html/src/Application.php(64): Cake\Http\BaseApplication->addPlugin('CsvView')
#3 /var/www/html/vendor/cakephp/cakephp/src/Http/Server.php(120): App\Application->bootstrap()
#4 /var/www/html/vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Server->bootstrap()
#5 /var/www/html/webroot/index.php(40): Cake\Http\Server->run()
#6 {main}

```

**Comment by dereuromark** [comment]
Did you composer install it?
