### ISSUE TITLE
unable to unit test for downloads

### ISSUE THREAD

**Issue by liaogz82** [FriendsOfCake/cakephp-csvview#93]
I have an implementation of your library that works in the browser, but when I run the unit test below

```
  public function testReportsExportAuthenticated(){
      // Set session data
      $this->session([
          'Auth' => [
              'User' => [
                'id' => 1,
                'username' => 'admin',
                'name' => 'Admin',
                'phone_number' => '1234'
              ]
          ]
      ]);
      $this->get('/reports/export');
      $this->assertResponseOk();
   }
```

the assertResponseOk throws me an error 500. How is it so?

**Comment by josegonzalez** [comment]
What is the stacktrace ?

**Comment by liaogz82** [comment]
very strange stacktrace

```
2018-07-06 09:25:08 Error: [Error] Call to a member function user() on boolean
Request URL: /reports/export
Stack Trace:
#0 /var/www/html/src/Controller/ErrorController.php(54): App\Controller\AppController->beforeRender(Object(Cake\Event\Event))
#1 /var/www/html/vendor/cakephp/cakephp/src/Event/EventManager.php(416): App\Controller\ErrorController->beforeRender(Object(Cake\Event\Event))
#2 /var/www/html/vendor/cakephp/cakephp/src/Event/EventManager.php(393): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#3 /var/www/html/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php(110): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#4 /var/www/html/vendor/cakephp/cakephp/src/Controller/Controller.php(610): Cake\Controller\Controller->dispatchEvent('Controller.befo...')
#5 /var/www/html/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(325): Cake\Controller\Controller->render('pdo_error')
#6 /var/www/html/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(200): Cake\Error\ExceptionRenderer->_outputMessage('pdo_error')
#7 /var/www/html/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(118): Cake\Error\ExceptionRenderer->render()
#8 /var/www/html/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(100): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(PDOException), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 /var/www/html/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 /var/www/html/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 /var/www/html/vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 /var/www/html/vendor/cakephp/cakephp/src/TestSuite/MiddlewareDispatcher.php(97): Cake\Http\Server->run(Object(Cake\Http\ServerRequest))
#13 /var/www/html/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestCase.php(485): Cake\TestSuite\MiddlewareDispatcher->execute(Array)
#14 /var/www/html/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestCase.php(373): Cake\TestSuite\IntegrationTestCase->_sendRequest('/reports/export', 'GET')
#15 /var/www/html/tests/TestCase/Controller/ReportsControllerTest.php(45): Cake\TestSuite\IntegrationTestCase->get('/reports/export')
#16 [internal function]: App\Test\TestCase\Controller\ReportsControllerTest->testReportsExportAuthenticated()
#17 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(1072): ReflectionMethod->invokeArgs(Object(App\Test\TestCase\Controller\ReportsControllerTest), Array)
#18 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(940): PHPUnit\Framework\TestCase->runTest()
#19 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php(698): PHPUnit\Framework\TestCase->runBare()
#20 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(895): PHPUnit\Framework\TestResult->run(Object(App\Test\TestCase\Controller\ReportsControllerTest))
#21 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#22 /var/www/html/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(546): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#23 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(195): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#24 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(148): PHPUnit\TextUI\Command->run(Array, true)
#25 /var/www/html/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#26 {main}
```

**Comment by josegonzalez** [comment]
Maybe the test controller doesnt invoke initialize?

**Comment by liaogz82** [comment]
ok so how do i invoke initialize on the test controller?

**Comment by josegonzalez** [comment]
Make sure your sub-classed controller calls the parent methods if it overrides them.

If you continue to have issues, this sounds like a generic cakephp testing problem - not one to do with this plugin. I would ask in the cakephp slack/irc channel if you have further questions, as thats a better venue for support on the framework.
